### ISSUE TITLE
(newb) out of date libraries

### ISSUE THREAD

**Issue by yatesco** [shadaj/create-react-scala-app.g8#19]
Hi there, is it possible to get a version of this with the latest 2.13 versions or even Scala 3?

I spent a few hours trying and it was way beyond my skill set unfortunately.

As it stands, importing a newly created project causes VSCode and Metals to complain and offer reduced functionality.

Thanks!

**Comment by shadaj** [comment]
Just pushed up an update that brings all the versions up to date! The template is still on 2.13 though, since Scala 3 support isn't there just yet for Slinky.

**Comment by yatesco** [comment]
Works perfectly - thank you @shadaj
